name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nodeModules-
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nodeModules-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        node: [12, 14, 15, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: matrix-nodeModules-${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            matrix-nodeModules-
      - run: yarn install --frozen-lockfile
      - run: yarn test-only
  release:
    needs: [lint, build, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            nodeModules-
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
